dropout: 0.1
chara_nums: 11172
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 128
num_channels: 128
num_res_blocks: 3
batch_size: 2
num_samples: 2
attention_resolutions: '40, 20, 10'
use_ddim: True
timestep_respacing: ddim25
stroke_path: './korean_stroke.txt'
model_path: './trained_models/ema_0.9999_700000.pt'
sty_img_path: './1.png'
total_txt_file: './total_kor.txt'
gen_txt_file: './gen_char_kor.txt'
img_save_path: './result'
classifier_free: True
cont_scale: 3.0
sk_scale: 3.0